### ISSUE TITLE
Error on init

### ISSUE THREAD

**Issue by pplanteg** [slydiman/ha_custom_onvif#7]
Hi
I'm trying to use your custom onvif intergration but i have this error on startup :

Can you help Please ?

Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.config
Source: custom_components/onvif/__init__.py:5
Integration: ONVIF
First occurred: 07:38:48 (1 occurrences)
Last logged: 07:38:48

Platform error: camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 887, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/onvif/__init__.py", line 5, in <module>
    from homeassistant.const import (
ImportError: cannot import name 'Platform' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by slydiman** [comment]
What version of Homeassistant are you using?

ha_custom_onvif v2021.12.12 requires at least Homeassistant v2021.12.0.

You can try some previous version of ha_custom_onvif:
https://github.com/slydiman/ha_custom_onvif/releases

**Comment by pplanteg** [comment]
Ah yes it could be that..
I’ll give a try tomorrow and let you know

thanks

**Comment by pplanteg** [comment]
hello,
That was my problem, it running fine now.
But still no discovery of sensors nor ptz for my camera :( 
I only have main and second stream added.

my camera is a Ctronic "Device type : C6F0SoZ3N0PcL2" and have sensor and ptz working with "ONVIF Device Manager" on Win10.

Any idea ?

thanks a lot for your help.

**Comment by pplanteg** [comment]
Update PTZ is working but no sensor 
If it could help you finding a solution for me, here screen capture of onvif manager :

<img width="888" alt="Capture" src="https://user-images.githubusercontent.com/33163950/150744135-68f8d672-c036-4253-ad36-6428ed02c7df.PNG">
<img width="269" alt="Capture2" src="https://user-images.githubusercontent.com/33163950/150744152-e5cc4030-79c1-4a36-bddb-4b4bb24b5b27.PNG">

**Comment by slydiman** [comment]
The topic `tns1:RuleEngine/CellMotionDetector/Motion` is exist in the event parser.
Please check the log of HomeAssistant for more info.
Probably you need to enable the debug log in configuration.yaml:
```
logger:
  default: info
  logs:
    homeassistant.components.onvif: debug
    zeep.transport: debug
    custom_components.onvif: debug
    zeeep.transport: debug
```

Note sometimes the log did not help. I have recorded the traffic between HomeAssistant and the camera using WireShark to investigate the issue.
